package servant.domain;

import java.util.ArrayList;

import servant.persistence.ServantDao;
/*import servant.persistence.ServantDaoImpl;*/

public class ServantService {
/*private ServantDao dao=new ServantDaoImpl();*/
	ArrayList<Servant>servants;
	public ServantService() {
		Servant s1=new Servant(82, "Frankenstein", "Frankenstein's monster","Female","Berserker",9441, 10687, "Earth","The artificial life form created by Victor Frankenstein.\r\n" + 
				"Built as the Eve that forms a pair with Adam, because her expressing of human emotions does not function well, she was branded a failed work.","Berserker's True Name is Frankenstein (フランケンシュタイン, Furankenshutain?), the Frankenstein's monster (フランケンシュタインの怪物, Furankenshutain no Kaibutsu ?). Based upon the artificial life created by Victor Frankenstein in Mary Shelley's novel \"Frankenstein: or the Modern Prometheus\". Victor sought to recreate the original couple described in the bible -- Adam and Eve. Due to the limitations of man, he first built Eve, intending for her to give birth to the counterpart. What started as a patchwork of lifeless flesh was given life by the energy harnessed from lightning. Unfortunately, what awoke was not the ideal woman that Victor envisioned, but an abomination with the mind of an infant. Having no developed capacity for expression, her sense of morality was completely absent. After presenting the entrails of a slain dog as a gift for the master, she was branded a failure and disassembled, before being abandoned completely.","Berserker is a lovely young girl clad in a white dress with empty eyes, carrying a giant mace. Her eyes are normally covered by her long hair and only peek between the gaps. While Frankenstein is known for being a tall man over two meters tall, reminiscent of the portrayals of Boris Karloff and Robert de Niro, she resembles the Bride of Frankenstein at first glance. Due to her appearance, Caules is confused as to whether Victor Frankenstein had a twisted sense of beauty when looking upon her and calling her repulsive, or if she possesses an inconcealable foulness despite her external beauty.","What started as a patchwork of lifeless flesh was given life by the energy harnessed from lightning. Unfortunately, what awoke was not the ideal woman that Victor envisioned, but an abomination with the mind of an infant. Having no developed capacity for expression, her sense of morality was completely absent. After presenting the entrails of a slain dog as a gift for the master, she was branded a failure and disassembled, before being abandoned completely.\r\n" + 
				"\r\n" + 
				"Though still in pieces, she still lived, and over a period of time, was able to reconnect and repair herself. In her former master's absence, she came into contact with the outside world, and developed the emotions and feelings that could never be created in the first place. Thus she realized a great anger towards the one who abandoned her, but also admiration for the one who was effectively her father. She doggedly pursued the man until finding him in Geneva, Switzerland, where she made the following appeal:\r\n" + 
				"\r\n" + 
				"However, he flatly refused. Believing himself to have birthed of a hideous creature, it seemed unthinkable to even consider creating another. Though she pleaded, he denied her again and again, causing her to realize the truth and fall into deep despair. She decided that she must have him create another no matter what, so she killed those acquainted with him, those with no relation at all, and even his fiancee. He continued to flee from her despite that, denying her request to the end.\r\n" + 
				"\r\n" + 
				"Getting tired of her persistent chase, Victor fled to the South Pole, choosing to die over granting her one wish. Dying in madness, he regretted her creation until his last breath. With the man she had looked up to gone and without anyone to hate, she parted from Walton, the man who watched over Frankenstein's final moment, and traveled to the uttermost north. She built herself a pyre, allowing herself to be consumed by the flames while thinking, \"May my ashes be scattered across the seas...\" That was the end of the monster born from the delusions of Frankenstein.", 172, 48, "Europe");
		Servant s2=new Servant(199,"Sermiramis","Wise Queen of Assyria","Female","Assassin",11309,13266,"Earth","The oldest known poisoner in the world, and Empress of the Assyrian Empire. By poisoning her husband Ninus, she rose her name in one stroke. \r\n" + 
				"For a period of time, it was rumored that she was the one who constructed one of the Seven Wonders of the Ancient World, the 'Hanging Gardens of Babylon' (which were really constructed under the reign of Nebuchadnezzar II)","Assassin's True Name is Semiramis (セミラミス, Semiramisu?), Wise Queen of Assyria (アッシリアの賢女王, Asshiria no Ken-Joō?). Born from the Syrian mermaid goddess Derketo and a human man, she was left on the waterfront by her loveless mother. She was wrapped in the warm wings of a dove, and fed with the dove's milk. Semiramis was then found and educated by the shepherd Simmas until she married Onnes, an old general; but she was then taken away by the Syrian king Ninus who fell in love with her thanks to her beautiful face. This forced Onnes to commit suicide, and after Semiramis earned the favors of the king with original battle plans, she married him and formally became queen. A few days after the marriage, she killed the king with poison, and reigned as a regent over Assyria for the next few decades. This is the oldest case of murder by poisoning in legends.","Assassin is described as a \"depraved beauty\" and a \"peerlessly beautiful woman\" wrapped in a dress as \"dark as midnight\" who emanates a pleasing aroma.","Semiramis was born between the Goddess Derketo and a human, and ashamed of that fact, Derketo abandoned her by the water's side. \r\n" + 
						"But as a baby carrying the blood of the god, she was brought up by countless doves and given a new lease on life. \r\n" + 
						"Growing up beautifully, Semiramis was wed to the aging general Onnes, but the ambitious King Ninus captivated by her face half-forcefully parted her from her husband. Led to sorrow, Onnes committed suicide, and Semiramis was left with no choice but for her body to accept the King's grace.\r\n" + 
						"When the novel tactics Semiramis suggested in a war with foreign lands landed them a victory, King Ninus came to know of her splendid talent, finally deciding a formal marriage with her.\r\n" + 
						"But the moment King Ninus put his lips to his wine glass at the wedding banquet, he suddenly collapsed in pain and died. It is rumored that she laced it with poison to take revenge for her late husband. \r\n" + 
						"And thus having become Empress of Assyria, Semiramis took over the duties of managing governmental affairs for many decades, spearheading numerous expeditions and construction projects.\r\n" + 
						"Afterwards, it's been said she was murdered by her son, or perhaps after handing off power she became a dove and flew away.",169,51,"Middle East");
		Servant s3=new Servant(2,"Artoria Pendragon","King of Knights","Female","Saber",11221,15150,"Earth","A legendary king of Britain. Also called the King of Knights.\r\n" + 
				"Altria is a childhood name and, upon being raised as a king, she began to be called King Arthur.\r\n" + 
				"In an age when chivalry had lost its beauty, with a holy sword in her hands, she brought about a brief moment of peace and final prosperity to Britain.\r\n" + 
				"A man in historical fact, but it seems that in this world she was a cross-dressing beauty.","Saber's True Name is Artoria Pendragon, better known as Arthur Pendragon and King Arthur, who is regarded as a male in history. She is the \"Once and Future King\" and a legendary hero of Britain known as the King of Knights (騎士王, Kishi-Ō?). She wielded the sword from the stone, Caliburn, but it was eventually destroyed. She later obtained Excalibur and Avalon from the Lady of the Lake.","Saber has the appearance of a young woman in her late teens with a slender physique, soft skin, and green eyes. She has \"finely textured\" blonde hair that seems \"as if sprinkled with gold dust.\" Her face shows some signs of naivety and displays elegance. She is more muscular than someone like Rin, leading her to believe her body is unappealing, but Shirou believes her to be very feminine. She normally wears shining armor with an old styled dress, made from old-fashioned blue cloth, underneath. She is actually older than her appearance would show, as her body did not age from the moment she pulled Caliburn from the stone to the time of her death. Shirou sees her as being a few years younger, and the age of her body is probably a year younger than him. Though she lived as a man most of her life, Shirou and Rin describe her as beautiful instantly upon seeing her. Despite her armor being unrefined and unaesthetic, Shirou describes Saber as being beautiful enough to make the steel clanking of her armor seem like the chiming of a bell.","Artoria led Britain from Camelot, and after becoming a feudal lord like her father, she became a king with many knights under her, including the esteemed Knights of the Round Table. Her growth stopped at that time she pulled the sword because of its magic, so many knights feared it as ominous. Most instead praised their master's immortality as divine. Her battles thereafter were the acts of a god of war. She always led from the front, and no enemies could stand in her way. There was no defeat for a body admired as a dragon in human form. She only knew victory for ten years and twelve battles while she ran through those days as the king. She never turned back and was never disgraced. She was raised as a king and fulfilled her obligations as the king.",154,42,"England");
		Servant s4=new Servant(94,"Astolfo","One of the Twelve Paladins of Charlemagne","Male","Rider",8937,11172,"Earth","Astolfo is a character from the legend of Charlemagne, Frances most famous tale of chivalry.\r\n" + 
				"One of the Twelve Paladins of Charlemagne, and a prince of England.\r\n" + 
				"Additionally, a screwed-up Heroic Spirit who has lost all rationality.","Rider's True Name is Astolfo (アストルフォ, Asutorufo?), one of the Twelve Paladins of Charlemagne (シャルルマーニュ十二勇士, Sharurumānyu Jūni Yūshi?). In the Charlemagne Legend, he is the son of an English king, and one of Charlemagne's twelve faithful Paladins. Among the Twelve Paladins of Charlemagne, Astolfo is said to be the most handsome, eternally optimistic, and completely lacking in sense. As the legends go, Astolfo was quite the ladies' man. As a cousin of Roland, Astolfo is included among those twelve-- that being said, Astolfo was famed as \"weak\" in legends." ,"Rider is an androgynous-looking boy who is fancily dressed. Beautiful beyond all compare, he states that his hair ornaments, which seem like something a princess would wear, are an \"irresistible proof of friendship\" that he uses to restore peace to his depressively mad boon ally, Roland. His appearance is contrary to the legend of being said to be the most handsome among the Twelve Peers of Charlemagne, and though extremely unexpected, it is natural for legends to become distorted. He purposefully dresses as a girl because he likes cute things. His gender in the servant status was written \"le Secret♪\".","Astolfo has created many legends as he was an adventurer who flew to all over the world and even reached the Moon in the end. Through his journeys, he had won numerous Mystic Codes such as his flute, his grimoire, and his shining golden lance. Astolfo brought rise to various legends on the back of mounts like a griffin and the famous Rabicano, but particularly famous among them is something inconceivable for this world—the Hippogriff.\r\n"+
"Although many are the glorious tales of Astolfo, it is said that he has made just as many mistakes. He was continually defeated in riding tournaments, fell victim to many thaumaturgical traps and even lost—in a matter of hours—the reason that he had picked up at the moon. However, Astolfo never faltered; he did not seem to consider failure or defeat as blunders in the first place.",164,56,"France");
		Servant s5=new Servant(196,"Ereshkigal","Goddess of the Underworld","Female","Lancer",10343,16065, "Earth","The Goddess of the Netherworld in Sumerian myth. She freely wields a spear-like cage; at times stabbing the enemy with, at times imprisoning souls, at times summoning lightning, she is the fearsome ruler of the netherworld.\r\n" + 
				"Having carried out her duties of administrating the netherworld since birth, she is a goddess that disappeared along with the Age of Gods without ever knowing of the world above, or of freedom.\r\n" + 
				"This form is not that of the Goddess Ereshkigal, but that of a Pseudo-Servant where she has possessed the soul of a human with a similar wavelength to hers.","Lancer's True Name is Ereshkigal (エレシュキガル, Ereshukigaru?), the Goddess of the Underworld in Sumerian myth. She freely wields a spear-like cage; at times stabbing the enemy with it, at times imprisoning souls, at times summoning lightning, she is the fearsome ruler of the underworld. Having carried out her duties of administrating the underworld since birth, she is a goddess that disappeared along with the Age of Gods without ever knowing of the world above, or of freedom.\r\n" + 
				"\r\n" + 
				"This form is not that of the Goddess Ereshkigal, but that of a Pseudo-Servant where she has possessed the soul of a human with a similar wavelength to her's, Rin Tohsaka.","Lancer has a similair appearance to Tohsaka Rin, except for the red eyes and blond hair. She likes to dress in black and red.","In original Mesopotamian texts, she presided over the growth and decay of crops, bent the dragons and snakes to her will, and freely controlled the Garula familiars of the underworld. The 'Heavenly Mistress' Ishtar, and the 'Queen of the Great Below' Ereshkigal held a rival relationship. Mythologically speaking, the goddess of the harvest Ishtar (Inanna) was the Great Earth Mother that represented human life while Ereshkigal, who represented human death, was the Terrible Earth Mother.\r\n" + 
						"\r\n" + 
						"In the tale of Ishtar's descent, Ishtar made a visit to the underworld only to be killed by Ereshkigal's hand. While she was revived afterward, the reason Ishtar went down to the underworld, and the reason Ereshkigal was so enraged, are never spoken of, and in Fate/Grand Order, they are treated as stemming from them being one and the same. Ereshkigal and Ishtar. Two gods of equivalent existence, or perhaps a divinity divided from what was once a single entity.",159,47,"Mesopotamia");
		Servant s6=new Servant(12,"Gilgamesh","King of Heroes","Male","Archer",12280,13097,"Sky","Before the Modern Era, this demigod king governed the Sumerian city-state of Uruk.\r\n" + 
				"The king described in mankind's oldest epic poem, the \"Epic of Gilgamesh\", he is considered to have existed not only in legends, but also in reality.","Archer's True Name is Gilgamesh, the great half-god, half-human king born from the union between the King of Uruk, Lugalbanda, and goddess Rimat-Ninsun. He ruled the Sumerian city-state of Uruk, the capital city of ancient Mesopotamia in the B.C. era. He was an ultimate, transcendent being so divine as to be two-thirds god and one-third human, and no others in the world could match him. He was a despot possessing high divinity who believed he was invincible. He is not merely a legend, and is said to have actually existed and ruled during the Sumer Dynasty five thousand years ago. He was the King of Heroes (英雄王, Eiyū-Ō?) who possessed all things in the world, whose tale is recorded in mankind's oldest epic poem, the Epic of Gilgamesh which portrays Gilgamesh as a hero, destined to be king and achieve great feats, who is driven to meet his destiny, facing challenges together with his best friend Enkidu","Gilgamesh is a tall and dignified young man with golden hair standing up like a blazing flame. He is described as handsome with an handsome face, and his eyes, crimson like blood, are visibly not those of a human and give off a mysterious radiance that makes people wither. He has a \"perfect, Golden-proportioned body\" described as emanating majesty that makes flames surrounding him afraid to come close, and his very soul glows golden. He normally wears golden armor that makes a heavy first impression on those he encounters. While fighting at full power in Fate/hollow ataraxia, he gains a number of red tattoos on his body that are not normally present","Born with a body that was of the highest grade by mortal standards and knowledge reaching truth, Gilgamesh was born, designed, as king and the Keystone of Heaven between the rising humans and the fading gods. He was sent to ensure the humans and bind the earth slowly leaving the Age of Gods. He was a being embodying the two life sets of life forms, with the blood of those who had ruled and the blood of those who would rule from thereon. He was to be the ultimate neutral party able to discern their respective failings, adjudicating from their respective positions. During his childhood, he loved the gods instead of humanity, but the gods created Enkidu at that time to punish the arrogant king.\r\n" + 
				"\r\n" + 
				"Enkidu observed the young Gilgamesh, but could not understand the need to punish such an amiable, ideal king who was praised and lauded by his infatuated subjects. There could be no flaw that required correction, and the only problem was that he did not submit to the gods even if he did respect them. Enkidu was forced to admit that the gods had been correct as he watched the boy grow into a young man. Practicing absolutism, oppression, duress, levies, and the utmost decadence from self-interest, the people of the kingdom lamented the change, and even the gods were perplexed at the extent of the expected transformation.\r\n" + 
				"\r\n" + 
				"The reason was simply that he had been born with the conclusion already drawn, existing independently as a being neither fully divine or human. He acquired the characteristics of both, so his field of vision reached even past what the gods were able to comprehend. His overwhelming power bred overwhelming isolation, but his strength of self kept him from abandoning his kingship or fleeing from the mission imposed upon him. Through revering the gods and loving humanity, he decided to follow the path to its conclusion by deposing the gods and loathing humanity.",182,68,"Babylonia");
		Servant s7=new Servant(59,"Jeanne d'Arc","Holy Maiden Savior","Female","Ruler",9593,16500,"Star","The most famous holy woman in the world. Between departing from her home town at 17 years-old and being sentenced to the stake at 19 years-old, she carved her name on history in mere two years.\r\n" + 
				"The holy woman that saved France; after accomplishing a military advance that could be very well be described as miracle, she was scorned and met a tragic end.","Ruler's True Name is Jeanne d'Arc, the Saint of Orleans. A Catholic saint born in Domrémy, France, and the heroine of France who liberated Orléans in the Hundred Years' War.","Ruler possesses the body of a French girl named Laeticia whose physical build, spiritual build, personality and Magical Energy were compatible to her. But her bust size alone is just slightly bigger than Jeanne d'Arc. Her eyes were described as amethyst-colored eyes and they were completely pure. She didn’t have the precise and molded beauty of a homunculus, or the kind of cuteness that made one’s heart flutter just by being nearby like Rider of Black. She possessed a wondrous beauty that scarcely felt real. In her battle mode, she can transformed into her battle-dress with armour woven from Magical Energy to enclose her. Under her gauntlet, she has Command Spells engraved on her hand, where as those special to command the Servants during the Great Holy Grail War are printed on her back with a similar shape drawn that of an angel. Although Gilles mistook King Arthur as Jeanne d'Arc, the main difference between her and King Arthur's appearance is sex appeal.","The most famous holy woman in the world. Between departing from her home town at 17 years-old and being sentenced to the stake at 19 years-old, she carved her name on history in mere two years.\r\n" + 
						"The holy woman that saved France; after accomplishing a military advance that could be very well be described as miracle, she was scorned and met a tragic end.Even after being captured, Jeanne kept making miracles.\r\n" + 
						"It has been said that a farm girl - who should know nothing but the Bible and a few words of prayer - aptly maintained an argument with a first-class theologian on equal terms, making difficult to punish her as a heretic.A soldier that declared that he would gladly burn a witch as evil as Jeanne of Arc witnessed a white dove fly towards France, after the young woman burned.\r\n" + 
						"It was then, he lamented with deep regret, that he knew they had murdered a true saint…",159,44,"France");
		Servant s8=new Servant(68,"Okita Sōji","Sakura Saber","Female","Saber",12068,13225,"Man","Okita Souji; captain of the First Unit of the Shinsengumi, a public order organization that was mostly active in the Kyoto of the Edo period's closing days.\r\n" + 
				"Even among the Shinsengumi, which was feared as a band of master swordsmen, the one admired as the strongest genius swordsman was Okita.","Sakura Saber's True Name is Okita Souji (沖田総司, Okita Sōji?), the captain of the first unit of the Shinsengumi, a public order organization that was mostly active in the Kyoto of the Edo period's closing days. Even among the Shinsengumi, which was feared as a band of master swordsmen, the one admired as the strongest genius swordsman was Okita.","Okita Souji is a female in history and she looks similar to King Arthur. A lovely girl in her mid-teens, who wraps her body in fashionable Japanese clothing. In order to conceal her original costume, which is simply too conspicuous, Okita normally uses this outfit, wearing a Taisho-style Kimono that consists of a Hakama and long leather boots.","During her childhood, while she was still an apprentice at the Shieikan, the dojo of the Tennen Rishin-ryuu in Edo's Ichigaya area, Okita Souji met Hijikata Toshizo and Kondo Isami, core figures of the Shinsengumi in the future. She was skillful enough to serve as the head coach of the Shieikan at a young age, and there was no person who was superior to her regarding the talent with the sword.\r\n" + 
						"\r\n" + 
						"Kondo formed the Roshigumi on behalf of being bodyguards for the Shogun in the third year of the Bunkyuu era, and Okita went to the Imperial Capital to participate in the group together with Hijikata. After the break up of the Roshigumi, Kondo formed the Shinsengumi together with Hijikata, and Okita was entrusted with the position of captain of the first unit.\r\n" + 
						"\r\n" + 
						"Demonstrating their sword abilities in many conflicts like the Ikedaya Incident and so forth, the name of the Shinsengumi roared throughout Kyoto of the Bakumatsu era. However, Okita's body was adversely affected by an illness around that time, and her physical condition gradually deteroriated. Before long, she withdrew from the frontlines for medical treatment.\r\n" + 
						"\r\n" + 
						"Afterwards, Okita continued her life of recuperation while separated from her comrades, but in the fourth year of the Keio era, she died at the place where she was medically treated in Edo's Sendagaya area. It is said that she died without knowing of Kondo's death, who was decapitated two months prior to her death.",158,45,"Japan");
		Servant s9=new Servant(69,"Oda Nobunaga","Devil King of the Sixth Heaven","Female","Archer",9494,11637,"Man","The soldier of fortune from the Warring States Period, Oda Nobunaga.\r\n" + 
				"While she was called the \"Big Fool of Owari\" in her childhood, she made a name for herself in the world upon defeating Imagawa Yoshimoto in Okehazama.\r\n" + 
				"Afterwards, she eliminated many formidable enemies one after the other and even had the unification of the country within reach of her hands, but passed away in Honnouji thanks to the insurrection of Akechi Mitsuhide.","Demon Archer's True Name is Nobunaga Oda (織田信長, Oda Nobunaga?), the legendary warlord of the Sengoku and Azuchi-Momoyama Periods of Japan, and older sister of Oda Nobukatsu. Her moniker \"Devil King of the Sixth Heaven\" (第六天魔王, Dairokutenmaō?) was based on the severe acts of destruction carried out during her campaign.","Her clothing that looks like a military uniform is something she prepared herself out of hobby upon being summoned as a Servant.","The soldier of fortune from the Warring States Period, she was called the \"Big Fool of Owari\" (尾張の大うつけ, Owari no Ōutsuke?) in her childhood. She made a name for herself in the world upon defeating Imagawa Yoshimoto in the Battle of Okehazama. Responsible for the de facto downfall of the Muromachi Shogunate, Nobunaga had great influence during the closure of a the long, turbulent war period lasting since the Ōnin War.\r\n" + 
				"\r\n" + 
				"One of the first to assimilate western inventions and tactical concepts into the art of war, she wielded both a technological and economic advantage against her foes, with efforts focused on the control and development important hubs of industry and a the establishment of policies emphasizing the promotion of results and individual merit. Her Noble Phantasm is based upon the rotating volley tactics employed by her troops, and its anti-army nature is drawn from her skilled leadership.\r\n" + 
				"\r\n" + 
				"Between 1560 and 1583, she eliminated many formidable enemies one after the other and even had the unification of the country within reach. Her campaign ended in Kyoto, at the temple of Honnō-ji, thanks to the insurrection of Akechi Mitsuhide.The one who succeeded her was her former vassal, Toyotomi Hideyoshi.",152,43,"Japan");
		Servant s10=new Servant(62, "Tamamo no Mae","Mizukume","Female","Caster",10546,14259,"Sky","A good-wife-aspirant, extravagant miko shaman.\r\n" + 
				"In the deathbed of the Heian Period, this peerless beauty served the retired emperor Toba.\r\n" + 
				"It has been said that she is the disguised appearance of the nine-tailed fox Hakumen Kinmou.\r\n" + 
				"For a number of reasons, in the end she was chased away from the imperial court and, after having a major decisive battle with humans in the fields of Nasu, obediently let herself be exterminated, or something.","Caster's True Name is Tamamo no Mae (玉藻の前, ?), a woman of astonishing beauty that served as a courtesan for Emperor Toba toward the end of the Heian era (794-1185). She is publicly known as a Kitsune (狐, ? lit. \"Fox\"), and is credited for catalyzing the downfall of the Shang dynasty, among other powerful regimes. In the Genpei Seisuiki, she is associated with Dakini Deva, a tantric deity whose Japanese interpretation rode upon a fox; her power is invoked in one of Taira no Kiyomori's schemes for political influence.\r\n"+
"In the Nasuverse, Tamamo no Mae is a soul originating directly from the sun goddess Amaterasu as her Bunrei (分霊, ? lit. \"separated spirit\") and therefore a higher order of being than the Earth Spirit of myth. Her manifested form is actually a  Yakanjackal  ( 野干ジャッカル , ?), who suffers the fate of bearing cursory resemblance to a Nine-Tailed Fox Spirit. She is also frequently mistaken for an Uka no Mitama, or one of the many fox spirit messengers under the employment of Inari Ookami.","Caster is a therianthrope being with the appearance of a human possessing fox characteristics such as the ears and tail. She doesn't mind being called a fox since she thinks they are cute especially their fluffy ears. Caster has yellow eyes and long pink hair that she keeps tied up.","As a child, she was said to be the human form of a white-faced, gold-furred nine-tailed fox. At the age of eighteen, she started serving the court of Emperor Toba, who had fallen in love with her at first sight. She became a court lady and called herself Tamamo-no-Mae. She would be his lady-in-waiting under her current name and was his favorite, possessing great beauty and knowledge. However, her divine origins would eventually be her undoing.\r\n" + 
		"\r\n" + 
		"One morning, her head had sprouted fox ears; she managed to conceal them for a month. From there, the exact accounts vary, but what is clear is that she was exposed as a fox by an Onmyouji. By her accounts, it was Abe no Seimei, who had been investigating the cause of Toba's mysterious illness. Whether or not Mizukume led the emperor on or their love was real is uncertain, and countless tales of the matter had differing answers.\r\n" + 
		"\r\n" + 
		"She fled from the inner sanctum of the Imperial Court. They sent hounds after her, and it was the first time in Japan that a fox had been hunted by Hounds. She fled and cried in the fields of Nasu (那須, ?) because she was hunted by those who claimed to love her. Foxes gathered around her, saying things like \"you have come a long way\", and \"what a rough journey you had\". She wished the foxes to understand her feelings and hoped they would encourage her. It was then she realized who she truly was when the fox comforted her, stating \"aah, what a fool I was\". She was betrayed and hunted by the humans who feared her. She did nothing wrong, she only tried to help them prosper. She was forced to flee the village simply because she was not human. Her infamy grew at the plains of Nasu after fleeing from the court, where she met an eighty thousand man army that was dispatched at the behest of the retired emperor to kill her. The soldier came screaming \"kill the fox demon!\", and she tried to apologize to them but nobody listened. She fought back, yelling \"all right, let's do this!\", and killed everyone.",160,49,"Japan");
		Servant s11=new Servant(1, "Mashu Kyrielight","Shielder","Female","Shielder",6791,10302,"Earth","The form of Mashu Kyrielite, a Chaldea clerk, who underwent a possession union with a Servant.\r\n" + 
				"This is called a Demi-Servant.","Shielder's True Name is Mash Kyrielight, a Demi-Servant human fused with the Servant Galahad. She herself initially does not know the identity of the Servant fused with her.\r\n" + 
				"\r\n" + 
				"In the year 2000, Mash was created from artificial fertilization and genetic editing. She is actually a Designer Baby, a magus genetically engineered under the orders of Chaldea's late director, ‎Marisbury Animusphere, to be a prime vessel for a Heroic Spirit's soul.", "Mashu is a timid-looking girl who has a nerdy appearance. She usually wears a white labcoat and glasses, but when she turns into a servant she gain a dark purple latex-like suit.","In the year 2000, Mash was created from artificial fertilization and genetic editing. She is actually a Designer Baby, a magus genetically engineered under the orders of Chaldea's late director, ‎Marisbury Animusphere, to be a prime vessel for a Heroic Spirit's soul. The project aimed to control the powers of Heroic Spirits by binding them to a compatible mortal vessel in order to produce Demi-Servants.\r\n" + 
						"\r\n" + 
						"In 2010, Chaldea perform their second Heroic Spirit summoning. While the project succeed in summoning and binding a spirit to Mash, the spirit failed to awaken. Galahad decried Chaldea's brutal experiments, but remained in the world to keep his host alive.\r\n" + 
						"\r\n" + 
						"After the research team deemed the project a failure, Mash was left to Chaldea's care. However, due to being a genetically engineered organism not dissimiliar to a Homunculus, her life-span was set since her conception. She was given eighteen years to live and while she was aware of this fact, she kept it a secret between herself and Dr. Romani her physician. By the start of the story, Mash has already lived sixteen years of her life giving her a mere two years left, at best.",158,46,"Chaldea");
		Servant s12=new Servant(112,"Shuten Douji","One of Japan's Three Great Monsters","Female","Assassin",11993,12825,"Earth","In the Heian Era, the king of Mount Ooe was a commander of many fearsome demons. \r\n" + 
				"There are many origin stories surrounding Shuten Douji. \r\n" + 
				"One goes that she was born on Mount Ibuki to Yamata-no-Orochi and a human girl, another says she descended as the Dragon King Kuzuryuu's godsend. But no matter what, she is the child of a dragon god: something she shares in common with a certain Sakata Kintoki.","Assassin's True Name is Shuten-douji (酒呑童子, Shuten-dōji?), one of Japan's Three Great Monsters. The boss that governed the Oni within the castle structure on Mount Ooe during the Heian period. There are various theories about Shuten-douji’s origins. There is a theory where she is considered the child of a human and the Great God Ibuki of Mount Ibuki (= Yamata no Orochi), and there is another theory where she is considered the heaven-sent child of Mount Togakushi (= Kuzuryuu). At any rate, she is the child of a Dragon God, possessing a shared background with Sakata Kintoki. Due to her anecdotes and vestiges, she is classified as an \"Anti-Hero\".","Shuten Douji looks like a young petite girl between the age of 12 and 14. She usually wears traditional Japanese clothing and always has a bowl of sake in her hand. She also has two long horns on her forehead.","Whether she is the direct “child” of the Great God Ibuki, or whether she is a “descendant” who succeeded its blood, it is not clear. In the end, Shuten-douji herself does not speak about her origins. The alias called Ibuki-douji is just something attached to her by Ibaraki-douji, who saw the true nature of Yamata no Orochi’s power in her. It may not be discovered that the person herself has forgotten her past and the likes of it. As long as there is beguiling alcohol, brilliant banquets and enjoyable performances, she has no regrets.\r\n" + 
						"\r\n" + 
						"And yet… it seems that Shuten-douji had not completely forgotten her past regarding the existence of Sakata Kintoki, one who possesses origins similar to her own (being the child of a man-eating witch and a Dragon God), the man hanging in her mind ever since the time when he was young.\r\n" + 
						"\r\n" + 
						"Shuten-douji's connection with Sakata Kintoki continues on since that time. She, in the form of a beautiful girl, met Kintoki, who then fell in love with her. Given that this companion was easy to tease on some occasions, she had a good time while being accompanied with snacks and alcohol. As far as Shuten is concerned, they are no more than drinking bouts, but as far as Kintoki is concerned, they are demonic banquets that would kill him if he took the atmosphere lightly.\r\n" + 
						"\r\n" + 
						"Because of the disappearances of young men and princesses at the Imperial Capital happening one after another, Abe no Seimei did a divination and ascertained the matter to be the deed of Shuten-douji. Raikou’s Four Heavenly Kings, lead by Minamoto no Raikou himself, was ordered to subjugate her, arriving at the Oni’s castle while dressed in itinerant Buddhist monk attires. At the banquet, Raikou and the others made Shuten-douji and her group drink poisoned sake, then attacked them while they were asleep, punishing them. The removed head of Shuten-douji’s attacked Raikou, but it is said that the attack was thwarted due to the latter’s helmet given by a god. They used foul play in killing Shuten-douji, which Kintoki greatly regretted to the point of wanting to wish for Shuten-douji's revival to meet her once again.", 145,46,"Japan");
		Servant s13=new Servant(5,"Nero Claudius","Emperor of Roses","Female","Saber",9449,11753,"Man","Self-styled, cross-dressing beauty.\r\n" + 
				"Despite being selfish and self-supremacist, she is cheerfully openhearted, an almighty, self-indulgent emperor who was loved by the people due to her child-like innocence.\r\n" + 
				"Her real name is Nero Claudius Caesar Augustus Germanicus.\r\n" + 
				"The Fifth Emperor of the Roman Empire.","Saber's True Name is Nero Claudius Caesar Augustus Germanicus (ネロ・クラウディウス・カエサル・アウグストゥス・ゲルマニクス, Nero Kuraudiusu Kaesaru Augusutusu Gerumanikusu?), the Fifth Roman Emperor. She had the reputation of a notorious tyrant whose rule was made up of schemes and poison as she oppressed all religious forces, especially Christians, and the Roman Senate during the period from 50 to 60 AD.","Saber is a blond-haired young girl of short stature. She has a great resemblance to another Saber, King Arthur, though there is no blood relationship between them. King Arthur was said to be a fusion between two individuals, one of whom was the Roman general Artorius so there is some form of a link. Self-styled, cross-dressing beauty.","During her youth, Nero was revered as a very competent judge who brought in several important lawsuits with her fairness and efficiency, though Claudius had forbidden her from doing so due to her young age. Nero eventually succeeded her stepfather after Agrippina murdered Claudius in the year 54 AD, she was enthroned emperor at the age of seventeen, which would have been extremely difficult with her origins.\r\n" + 
						"\r\n" + 
						"After claiming the throne, Nero gave out money to all citizens in celebration. She then abolished all indirect taxes. Predictably, the public adored Nero's generosity. Nero attempted to reform a depraved government and the corrupt senate, but her reforms were stalled and met with hostility. Conflicts with the senate erupted when Nero tried to unify the Roman Empire with some troublesome provinces. In contrast, Nero boasted tremendous popularity from the citizens, thanks to her generous policies; her care for diplomacy caused Britannia's relations in Rome to improve during later years, essentially making her the person who built the opportunity for the legend of King Arthur to be born. She was also highly praised by Persia, which lead to Rome being considered \"the country of Nero\" by Persia after her death.",150,42,"Rome");
		Servant s14=new Servant(70,"Scáthach","Queen of the Land of Shadows","Female","Lancer",11375,14825,"Star","A warrior-queen from Celtic - Ulster mythology.\r\n" + 
				"The queen and gatekeeper of the foreign territory - haunted realm called \"Land of Shadows\", a prodigy of spearmanship and Rune magic.\r\n" + 
				"Possesses a power immense enough to rule and close the gate of the \"Land of Shadows\", which is overflowing with countless ghosts. It has been said that she became the mentor of Cu Chulainn - who would later grow into the hero of Ulster - guiding him, teaching all sorts of techniques and even bestowing his favorite magic spear. She also instructed his son, Connla.","Lancer's True Name is Scáthach (スカサハ, Sukasaha?), a female warrior-queen from Celtic Mythology's Ulster Cycle. The queen and gatekeeper of the foreign territory/haunted ground called the \"Land of Shadows\" (影の国, Kage no Kuni?), she is a prodigy of spearmanship and Rune magecraft. She possesses a power immense enough to obtain control over and close the gate of the \"Land of Shadows\", which is overflowing with countless ghosts, to ward off the dead. It has been said that she became the mentor of Cú Chulainn - who would later grow into the hero of Ulster - guiding him, teaching all sorts of techniques and even bestowing his favorite magic spear. She also instructed his son, Connla.","Scáthach is an extremely beautiful woman. She has long purple hair and red eyes, and wears a full-body outfit that highlights her curvaceous body.","Throughout her battles, Scáthach eventually ceased being human and started to be closed off from the World, unable to die as a human. She was known to be a woman \"strong like a monster\" who many sought out for apprenticeship. At the age of sixteen, Cú Chulainn traveled to the Land of Shadows in search of fame, and she became his mentor, guiding him in the \"secrets of leaping\", teaching him runic magecraft, and granting him his favorite demonic spear, Gáe Bolg.\r\n" + 
						"\r\n" + 
						"With her serving as the master of many pupils at the same time, Cú Chulainn was close to his fellow pupil Ferdiad, his equal in arms, and both competed for the right to possess Gáe Bolg. During this period, they went to war with Aifewho in some versions of the legends was her sister from the neighbouring country, who in some versions of the legends was her sister, and although Scáthach argued with Cú Chulainn over not letting him into battle, she, Cú Chulainn and Ferdiad eventually \"caused hell together.\" Cú Chulainn captured Aife alive and became involved with her afterward, earning Scáthach's punishment. Upon Cú Chulainn eventually receiving Gáe Bolg, she lamented over her inability to be killed by him since she had already ceased being able to die, wishing that he had been born earlier. Although still young and having arrived to the Land of Shadows by the shortest route, he could only apologize while lamenting the fate of the woman he loved. Cú Chulainn and Ferdiad eventually left the Land of Shadows on the same day, and Scáthach did not see them off due to having already passed down all her teachings to them. Using her foresight, she was able to predict her beloved pupil's final moments. She later taught Cú Chulainn and Aife's son, Connla, as well.",168,55,"Ireland");
		Servant s15=new Servant(14,"Atalanta","Chaste Huntress","Female","Archer",8633,12476,"Earth","A famous huntress that appears in Greek mythology. She became famous after being the first one to drive in an arrow during the extermination of the Calydonian Boar.\r\n" + 
				"Also, she is included as a member of the Argonautai, which assembled brave heroes from all over Greece.","Archer's True Name is Atalanta (アタランテ, Atarante?), a famous huntress known as the Chaste Huntress (純潔の狩人, Junketsu no Karyūdo?) that appears in Greek Mythology. She is a huntress who is famous for her swift feet in Ancient Greek legend. She became famous after being the first one to drive an arrow into the Calydonian Boar during its extermination. Also, she is included as a member of the Argonauts, which assembled brave heroes from all over Greece. She has the tragic past of being born as the daughter of a king of a certain country and yet being abandoned in the mountains by her father.","Atalanta is a huntress who wears beautiful green clothing, clad in verdant green with her cold, sharp eyes containing a beastly glint. Her hair is stretched out long and unkempt, and it is completely lacking in the silkiness that would be found amongst those of noble birth. As one who can be called a beautiful beast in human form, it befits her appearance.\r\n" + 
						"\r\n" + 
						"Atalanta's charm points consists of those things on her head that look like animal ears and that thing on her lower back that looks like a tail. Her animal ears and tail seem to be the symbols and after-effects of a curse told of in her legend... or so they should have been, but she actually seems to like them.","Atalanta was born as the daughter of King Iasus of Arcadia. However, although she was born in and as the princess of the natural paradise, Atalanta ended up being abandoned in the forests and on the mountains immediately she was born as she was shunned by her father - who desired a son. But she survived thanks to the divine protection from Artemis, a virgin goddess who felt pity for her. Artemis sent and made a female bear, a sacred beast of the goddess, nurture the girl by giving her milk and raising her up. In gratitude, Atalanta is a fervent follower of Artemis.\r\n" + 
								"\r\n" + 
								"Thereafter, after being brought up by the female bear sent by Artemis, and later was discovered and adopted by hunters who treaded into the mountains, Atalanta has developed her skills conspicuously, perhaps due to her latent talent, and also became a huntress. Upon reaching adulthood, Atalanta grows into and becomes an excellent and peerless huntress, and she accomplishes many adventures.",166,57,"Greece");
		Servant s16=new Servant(15,"Euryale","The Far-Flier","Female","Archer",7032,9506,"Sky","The middle sister of the Gorgon Sisters that appear in Greek Mythology.\r\n" + 
				"A goddess born as a perfected \"image (idol)\", \"the ideal young girl\" - the embodiment of men's longing. A young girl of loveliness, who is almost like purity and chastity given shape.\r\n" + 
				"Has an older sister, Stheno, and a younger sister, Medusa.","Archer's True Name is Euryale (エウリュアレ, Euryuare?) the Far-Flier (遠く飛ぶもの, Tōku Tobumono?), the second daughter of the Gorgon Sisters and the younger sister of Stheno and older sister of Medusa, who were goddesses born from the wishes of mankind for ideal idols, the embodiment of the yearning hearts of men. While she and Stheno were \"perfect goddesses\" who would not age, Medusa had some kind of flaw that allowed her to grow. They should have been three united sisters, but this divide allowed them to become three separate individuals.","Euryale and Stheno are identical sisters called the \"snow-white Gothic Lolita duo\". She wears a white frilly dress and has a white-and-black headband.","While Medusa was different from the start, her existence also brought irregularities in the two who were still the same. Due to the jealously of Athena, Medusa was cursed, had the faith of her followers taken away, and was banished to the Shapeless Isle as a monster. She called Stheno and Euralye monsters because they would never grow old, but that was a lie to cover the fact that they were \"perfected goddesses.\"\r\n" + 
						"\r\n" + 
						"Out of love for their younger sister, they also decided to live on the island although they were still worshipped. Living peacefully for a time, Medusa fought off men wishing to slay the rumored monster and those who wished to take their goddesses away by force. Loving to toy with men, heroes seeking to court them were met with impossible demands and forced back to their home countries only able to weep. While those challenging Medusa were petrified, those seeking marriage were ridiculed beyond reason until meeting their deaths. Due to a deep hatred developing for the humans, Medusa soon began to travel down the path of a monster. Though they warned her not to rejoice in killing humans, she began to feast on their blood and pleasurably seek out new methods of killing them. As even they began to fear her, she soon left her sisters when she could not bare to been seen in her slowly transforming state, eventually becoming the Gorgon.",134,30,"Europe");
		Servant s17=new Servant(18,"Elizabeth Bathory","Blood Countess","Female","Lancer",9122,11870,"Man","The Countess of blood that became the model for the vampire Carmilla. \r\n" + 
				"..or it should have been, but what was summoned as a Servant was her 14-year-old self from before she had committed any crimes.\r\n" + 
				"A sweet-type Servant who calls herself an idol.\r\n" + 
				"Noble, high-handed, cruel, merciless - she displays inhuman manners just like in legends.","Lancer's True Name is Elizabeth Báthory (エリザベート・バートリー, Erizabēto Bātorī?, lit. \"Erzsébet Báthory\"), the virginal fourteen year old aspect that had yet to become the monster Carmilla like her older aspect. She is given the keyword \"Dragon's Daughter\" (竜の娘, Ryū no Musume?), related to her nickname \"Countess Dracula\".\r\n" + 
						"\r\n" + 
						"A real person, born in 1560, died in 1614. She was born into the one of the noble families of Hungary, the Bathory family which uses the fang of a dragon as its crest. One of the models for the vampire Carmilla. A wicked woman who bathed in the living blood of more than 600 women in order to preserve her own beauty.","Elizabeth takes appearance of a young fair girl with mid-back length pink hair tied with purple ribbons and light blue eyes, which turns ice blue on occassions. She has slender figure and is claded in a cyber-goth-loli dress with white detached sleeves, with a circular skirt and several belts on the top connected to her collar that cover her chest area similar to Passionlip's, and wears knee-high shoes with two sharp spikes. She has long pink claws instead of fingers. Her most prominent features are the immoral devil horns (actually dragon horns), and the protruding fangs of a little devil (actually dragon fangs), along with a long draconic tail and pink scales scattered throughout her body. She wields lance that can double as a microphone stand. Her design doesn't seem to reflect her as a proper Heroic Spirit.","The Bathory house was the family who held the majority of the influence within Eastern Europe, and she increased that, possessing the blood of the house of Habsburg which made for a lineage that would make her a purebred noble. However, whether it is do to the consanguineous marriages within the Bathory line or the effect of their luxuriant living environment, the family contained many insane and cruel individuals. Among her close relatives were a homosexual and a pedophile; a Satanist is hardly worth mentioning.\r\n" + 
								"\r\n" + 
								"Elizabeth is not an exception and became quite infamous. In what is now present-day Slovakia, in Čachtice Castle, which resided within her own dominion, she killed more than 600 women and, in order to preserve her beauty, bathed in the blood she wrung from them... She loved those repulsive blood baths. This woman who killed many members of her fiefdom, even at the very end of her life, did not consider this a crime. In those days, there was a trend among the nobility of Hungary to not even consider humans who weren't nobles as \"humans\" so there were no problems with her murders.\r\n" + 
								"\r\n" + 
								"One day she let a maidservant comb the hair she was so proud of. But the comb got caught in her hair, and in a vehement rage, she stabbed the maidservant with a hairpin. The maidservant's blood happened to fall upon the back of her hand, and she noticed that the skin that blood touched was smoother than usual. From now on, to preserve my beauty, I will bathe in the lifeblood of women, she thought—and did so.",154,44,"Hungary");
		Servant s18=new Servant(23,"Medusa","Bewitching Black Serpent","Female","Rider",7200,8937,"Earth","The youngest of the Gorgon Sisters that appear in Greek Mythology.\r\n" + 
				"Originally an aboriginal Earth Mother Deity, but she had to run away to a shapeless island because of the Olympian Gods's stratagem and people's fanaticism. Once described as a snake monster that turns everything she sees into stone.","Rider's True Name is Medusa, the Gorgon from Greek mythology. Rather than being a regular Heroic Spirit, she is an existence closer to a Divine Spirit, but her actions have made it better to categorize her as an \"anti-hero closer to a monster.\" With her older sisters Stheno and Euryale, they made up the three Gorgon Sisters who inhabited the Shapeless Isle. She was known as the \"woman who dominates\", an anti-hero who became as such due to the dark thoughts of humans. Differing from someone like Hassan-i-Sabbah who was a hero who actually existed, she is said to be one of legends born by the gathering of belief.","The Medusa materialized in the Fifth Holy Grail War appears differently to her legend. She appears to be in her human form, unlike her legend where she has snake for her hairs, she has long purple hair.\r\n" + 
						"\r\n" + 
						"She wears an eye cover that seals her excessively powerful Mystic Eyes of Petrification within the Bounded Field. Her sight is completely sealed. Although Rider perceives the world through senses such as hearing, touch, smell, and magic-detection, she is able to acquire more precise information than sight.","She was originally considered to be a princess loved by humans, but Athena, jealous of their beauty, cursed Medusa alone, taking away her \"faith from each and every person\" and exiling her to the Shapeless Isle. Their love for her turned to hatred, and she was banished by those who had adored her. The island had nothing to offer compared to her days of luxury, and she prayed that none of the humans that now frightened her with their unwarranted resentment would tread on the island. Weeping in loneliness, she had no idea as to her sin that forced her to be exiled. Although her sisters were not affected and still greatly loved, they too accompanied her there out of caring for their younger sister. She was happy even on the barren island due to their company, and only had to fear the coming humans.\r\n" + 
								"\r\n" + 
								"While they became rumored as monsters, her sisters were still revered by nearby men, while she was feared as a monster. Humans sought to kill that which had been branded as a monster and take away the goddesses, and after they began to also target her sisters, she decided to protect them while taking her revenge on the humans. Although littered with statues that had been warriors, they were harmonious for a time on the island, at one point receiving her Pegasus from Poseidon. Though bullied by her sisters daily, she simply moved about the island on days humans did not appear, hoping for the peace to continue. Repaying them in the same manner as they treated her, she killed many humans, simply hoping to be left alone on the only place she could exist with the company of her sisters.",172,57,"Greece");
		Servant s19=new Servant(29,"Marie Antoinette","Queen of Lillies","Female","Rider",8293,12348,"Man","A French queen whose genealogy is related to the House of Habsburg.\r\n" + 
				"In the 18th Century, she was the queen of Louis XVI.\r\n" + 
				"Her existence symbolized the \"rule of the nobility\" of the European world.\r\n" + 
				"In an age of discord where the authority of royalty was being lost, she lost her life to the changes of the world.","Rider's True Name is Marie Antoinette (マリー・アントワネット, Marī Antowanetto?), the Queen of France of the 18th Century whose genealogy is related to the House of Habsburg. The queen consort of Louis XVI. An ephemeral lady. Born between Holy Roman Emperor Francis I, a person originating from the House of Lorraine as its Duke, and Maria Theresa, who is a descendant of the great aristocratic German household, the House of Habsburg, Marie was born and raised as an existence that symbolizes the \"rule of nobility\" of the European world, and during a chaotic period of human history where the right of monarchy was no longer absolute, she lost her life in a changing world.","Marie is endowed with the greatest body and good looks as the result of her being born so as to become a beautiful monarch that will be loved. Her attire is based on the concept of an \"Idol Queen\".\r\n" + 
						"\r\n" + 
						"During the Moon Festival event, Marie commented that in life, no matter how much food she ate, all the food would go to her breasts, making that the more she ate, the bustier she would get. d'Eon then confirmed it and stated through that, her Majesty would grow to have one of the finest bodies in France.","Loved as a symbol of royal authority, being blessed while living—Destested as a symbol of royal authority, shown contempt as she ended up dead. Protruding eyes of the nobility, political marriage, living the royal court life, and then, revolution and execution. It is possible to say that Marie's way of life and manner of death is the embodiment of royal authority as an evident \"idol\".\r\n" + 
								"\r\n" + 
								"Although a target of hatred by many people before, during and after the Age of Revolution, Marie's reputation has been restored in modern France; during famines, she reduced court expenses to make donations, personally demanded for the nobility to provide support to the people and such—it has thus being confirmed that she was a woman that thought of the people.",160,48,"France");
		
		
		Servant s20=new Servant(114,"Minamoto no Yorimitsu","Ushi Gozen","Female","Berserker",11556,13500,"Sky","An elegant, virtuous and glamorous woman in the prime of her youth. While a cool-headed military woman, Raikou is also a beautiful woman overflowing with tolerance. Surely the personification of maternal love.","Berserker's True Name is Minamoto no Raikou (源 頼光, Minamoto no Raikō?), also known as Minamoto no Yorimitsu, a person of the 10th~11th Century. Born as the eldest son of the Minamoto clan, he is a figure who contributed to the development of the entire Seiwa Genji line as the founder of the Settsu Genji branch. He is also the strongest Mystery Slayer of the Heian period who destroyed many monstrosities, such as “Shuten-douji of Mount Ooe”, the “Giant Spider (Tsuchigumo (土蜘蛛, ? lit. \"Earth/Dirt Spider\")) of the Imperial Capital”, and \"Ushi-Oni (牛鬼, ? lit. \"Ox-Oni\") of Sensou-ji”. Leading her subordinates, Raikou's Four Heavenly Kings (頼光四天王, Raikou Shiten'nō?) – Watanabe Tsuna, Sakata Kintoki, Urabe Suetake and Usui Sadamitsu – she continued to protect the peace of the capital. Naturally, he is a male in historical fact. As for the reason why she is a woman, it seems to be related to the secret of her birth.","An elegant, virtuous and glamorous woman in the prime of her youth. While a cool-headed military woman, Raikou is also a beautiful woman overflowing with tolerance. Surely the personification of maternal love.\r\n" + 
				"\r\n" + 
				"Raikou is a tall woman with a curvy figure. Her breasts are noticeably large. Also, she has very long hair. She uses a kind of latex bodysuit under some warrior clothes and armour.","The child of Minamoto no Mitsunaka, who was born as the heaven-sent child of Gozu Tennou, was left in the care of a temple as an unwanted child and was raised in secret because of his abnormal birth (being the child of an Oni). On the occasion of turning 15 years old, the unwanted child gave himself the name “Ushi-Gozen”, and he built up a demonic country for himself at Suzugamori, Shinagawa. The ones who departed to exterminate him was Minamoto no Raikou, a samurai who has the same father as him, and the Four Heavenly Kings that were commanded by Raikou.\r\n" + 
				"Meanwhile, it was Sakata no Kintoki who decided in his mind to save only Ushi-Gozen’s life during the extermination in any way possible. Away from the capital for a mission, Kintoki proceeded towards the base of Ushi-Gozen instead, but negotiations broke down. The subordinates of Ushi-Gozen were closed in and destroyed by the Four Heavenly Kings, as well as by Raikou, who were all accompanying Kintoki while hidden.\r\n" + 
				"Already up to this point, Gozen entered into the Asakusa River (Sumida River), and it would become the shape of a huge ox with a bodily height of approximately ten shaku, before it would spout water at the enemy armies, drowning many people to death. Ushi-Gozen was aware that the figures of the Four Heavenly Kings were not in sight among the enemy ranks, so he broke into a gallop towards the enemy camp, eight travelling horsemen, and seven strong samurai, before submerging to the bottom of Asakusa River and leaving these words behind: “One year, thunder will nominate someone in the capital.",175,52,"Japan");
		servants=new ArrayList<Servant>();
		servants.add(s1);
		servants.add(s2);
		servants.add(s3);
		servants.add(s4);
		servants.add(s5);
		servants.add(s6);
		servants.add(s7);
		servants.add(s8);
		servants.add(s9);
		servants.add(s10);
		servants.add(s11);
		servants.add(s12);
		servants.add(s13);
		servants.add(s14);
		servants.add(s15);
		servants.add(s16);
		servants.add(s17);
		servants.add(s18);
		servants.add(s19);
		servants.add(s20);
	}
public ArrayList<Servant> getAllServants(){
	return servants;
}
public Servant getServantById(int id) {
	Servant result=null;
	for(Servant s:servants) {
		if (s.getId()==id) {
			result=s;
		}
	}
	return result;
}
}
